Dev
GoogleCloudPlatform/genai-for-marketing pull request #104
Opened 2024-09-12 06:06 UTC by leelapriyabhatta

Added Spinner for export slides in activation page

2024-09-12 19:31 UTC, ghchinoy approved these changes
LGTM

2024-09-24 15:35 UTC, ghchinoy requested changes

2024-09-26 14:18 UTC, michaelwsherman commented on frontend/src/app/content-review/content-review.component.scss
> -    margin-top:20px
Leela verbally confirmed that she will fix this.

2024-09-30 09:24 UTC, leelapriyabhatta commented on frontend/src/app/content-review/content-review.component.scss
> -    margin-top:20px
> Removal of this makes the button too close to the top separator Consider re-adding

I did add the css and pulled the changes from dev branch and removed unused css in this file

2024-10-01 21:03 UTC, awaemmanuel commented
I don't still see a spinner @leelapriyabhatta. All I see is exported successfully at the bottom of page after waiting a while.

2024-10-02 00:43 UTC, awaemmanuel commented
> I don't still see a spinner @leelapriyabhatta. All I see is exported successfully at the bottom of page after waiting a while.
> 
> ![image](https://private-user-images.githubusercontent.com/3170798/372650070-115f9c46-d5bc-4fd3-964e-b7586ee340a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MzAwODksIm5iZiI6MTcyNzgyOTc4OSwicGF0aCI6Ii8zMTcwNzk4LzM3MjY1MDA3MC0xMTVmOWM0Ni1kNWJjLTRmZDMtOTY0ZS1iNzU4NmVlMzQwYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMDA0MzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTZlMWU5NGE3MDQxMmJlYTRmOGU2MjlmMjNlYjM1NmM3MDUyYzljZTA0MWJhZWMwMjdlZTU5ZTA3Yzc1MDYwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.sDy5QM2FFGVMLbCNEYKZeL7bNznyVjlm7TGkUH7NFLo)

I redeployed and see that the spinner is now working.

![image](https://github.com/user-attachments/assets/09bfb20b-0f57-4432-9339-df1d02d8887a)

2024-10-02 00:45 UTC, awaemmanuel commented
Tested the PR and spinner is present. I'll squash merge and close this PR. 

![image](https://github.com/user-attachments/assets/7627564c-b054-42b8-a502-e5bb5023adce)

2024-10-02 00:47 UTC, awaemmanuel approved these changes
LGTM

2024-10-02 14:43 UTC, ghchinoy approved these changes
LGTM

2024-10-02 14:43 UTC, merged