Gemini model configuration
GoogleCloudPlatform/genai-for-marketing pull request #110
Opened 2024-09-20 03:32 UTC by imp14a

Moving NL2SQL to use Gemini

2024-09-20 15:31 UTC, awaemmanuel commented
Everything else besides the ask to move hyperparameters to config. Also have you tested this PR?

2024-09-24 12:17 UTC, awaemmanuel commented
@imp14a the branch has conflicts now.

2024-09-24 14:36 UTC, michaelwsherman requested changes
Please confirm you've tested.

2024-09-24 14:36 UTC, michaelwsherman commented on backend_apis/app/main.py
> -gemini_llm = GenerativeModel("gemini-1.0-pro-001")
A couple issues here to resolve.
1 - gemini_llm is used in other methods, don't change the assignment of it. Load up the code model into a separate variable, maybe code_llm.
2 - model_version_name is a very ambiguous name because we have different models loaded and used all over the place in this file. code_model_version_name is fine, though you could probably do this as a oneliner (code_llm = GenerativeModel(config["models"]["code_model_name"]

2024-09-24 14:36 UTC, michaelwsherman commented on backend_apis/app/main.py
> -            llm=llm_ga,
change gemini_llm here too to whatever you name the code model.

2024-09-24 14:36 UTC, michaelwsherman commented on backend_apis/app/utils_codey.py
> +    except:
thank you for adding the try/except!

2024-09-24 14:36 UTC, michaelwsherman commented on frontend/src/app/audiences/audiences.component.html
> +        <option value="What are the customer emails ordered by the total transactions in app by the customer in the state of Georgia?">
this may run better as "all customers in the state of Georgia"

2024-09-24 20:25 UTC, merged