Fix: Remove manual deployment README and cleanup root and infra READMEs.
GoogleCloudPlatform/genai-for-marketing pull request #115
Opened 2024-09-23 23:45 UTC by michaelwsherman

This should complete the docs cleanup for 2.1.

- Manual deployment README deleted and no longer linked from root README. b/358367459
- Instructions on adding dashboards added into root README from manual deployment README and rewritten.
- Root README deployment section only points to terraform deploy. b/363338347
- A bit more info about frontend and backend deployment. b/363336571
- Add a link to Known Errors at the top of Deployment guide. b/369208289
- Deployment manager enablement in deployment prerequisites. b/367779528
- Made a pass of READMEs after cleaning everything above up. b/358367615

2024-09-23 23:51 UTC, ghchinoy requested changes
Minor comments

2024-09-23 23:51 UTC, ghchinoy commented on infra/README.md
> +You'll need to create a Google Cloud project and link a billing account before you begin. **It is strongly recommended you deploy Generative AI for Marketing in its own fresh project.** Existing reso
"... in its own, new project."

2024-09-23 23:51 UTC, ghchinoy commented on infra/README.md
> +Request access to Imagen3 through this [form](https://docs.google.com/forms/d/e/1FAIpQLSdMHAK_KJygnvV2Psga7FIzKAhAqIBS_bHYzfgf_Y2h7fsoGA/viewform). Note this can take up to a week. You can still use
'Imagen 3" (space between "Imagen" and the version number "3')

2024-09-23 23:51 UTC, ghchinoy commented on infra/README.md
> +The frontend of Generative AI for Marketing runs in Firebase. Before beginning deployment, you need to enable Firebase.
Consider "is hosted on" rather than "runs in"

2024-09-24 15:07 UTC, michaelwsherman commented on infra/README.md
> +You'll need to create a Google Cloud project and link a billing account before you begin. **It is strongly recommended you deploy Generative AI for Marketing in its own fresh project.** Existing reso
fixed

2024-09-24 15:07 UTC, michaelwsherman commented on infra/README.md
> +The frontend of Generative AI for Marketing runs in Firebase. Before beginning deployment, you need to enable Firebase.
fixed

2024-09-24 15:08 UTC, michaelwsherman commented on infra/README.md
> +Request access to Imagen3 through this [form](https://docs.google.com/forms/d/e/1FAIpQLSdMHAK_KJygnvV2Psga7FIzKAhAqIBS_bHYzfgf_Y2h7fsoGA/viewform). Note this can take up to a week. You can still use
fixed.

2024-09-24 15:33 UTC, ghchinoy approved these changes
LGTM

2024-09-24 15:33 UTC, merged